abstract class homestate{}
class initstate extends homestate{}
class changebotmNav extends homestate{}
class getDataLoading extends homestate{}
class getDataSucess extends homestate{}
class getDataError extends homestate{}
class getDataLoading1 extends homestate{}
class getDataSucess1 extends homestate{}
class getDataError1 extends homestate{}
class getfavLoading1 extends homestate{}
class getfavSucess1 extends homestate{}
class getfavError1 extends homestate{}
class addfavLoading1 extends homestate{}
class addfavSucess1 extends homestate{}
class addfavError1 extends homestate{}
class getsearchLoading extends homestate{}
class getsearchSucess extends homestate{}
class getsearchError extends homestate{}
class getprofileLoading extends homestate{}
class getprofileSucess extends homestate{}
class getprofileError extends homestate{}
class logoutLoading extends homestate{}
class logoutSucess extends homestate{}
class logoutError extends homestate{}